### ISSUE TITLE
Any build instructions?

### ISSUE THREAD

**Issue by zephchai** [Toolchefs/cameraLattice#1]
Hi,

I would like to know if there is any build instructions for this plugin? I tried creating a CMakeLists.txt to build it but I am getting some errors. Would you be able to tell me which Maya version this tool has been tested on?

Thanks,
Zeph

**Comment by danielefederico** [comment]
Hello Zeph,
we compiled it last for Maya 2018. Have you tried using Visual Studio and trying to start from one of the Maya sample projects? The camera lattice is a simple deformer.
Thanks

**Comment by zephchai** [comment]
Hi Daniele,

Thanks for the reply. I was able to build it after creating the CMakeLists.txt so all is good. On a side note, there is deprecation warning when building on Maya 2019.

Thanks,
Zeph
